# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Dux < Formula
  desc "Docker Use Context - Fast Docker context switching"
  homepage "https://github.com/nikitasova/dux"
  version "1.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/nikitasova/dux/releases/download/v1.1/dux_1.1_darwin_amd64.tar.gz"
      sha256 "ee3a1c543b492da913fb95dc0bdf4cd5ff100722b3b64f1151b4174f9feaece0"

      def install
        bin.install "dux"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/nikitasova/dux/releases/download/v1.1/dux_1.1_darwin_arm64.tar.gz"
      sha256 "9cf1a4c7fe9a35a92df6952914036bf9acba923e11fb941035ef1a91dc034455"

      def install
        bin.install "dux"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/nikitasova/dux/releases/download/v1.1/dux_1.1_linux_amd64.tar.gz"
      sha256 "6c2195caeb9d79381a677277824036a74e7956050c63a1f7876964fd4e0ca540"
      def install
        bin.install "dux"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/nikitasova/dux/releases/download/v1.1/dux_1.1_linux_arm64.tar.gz"
      sha256 "ff70114a71883e697b5aed6355a7180880fca970edc352711f1d19fbb9e67b12"
      def install
        bin.install "dux"
      end
    end
  end

  test do
    system "#{bin}/dux version"
  end
end
