# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Dux < Formula
  desc "Docker Use Context - Fast Docker context switching"
  homepage "https://github.com/nikitasova/dux"
  version "1.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/nikitasova/dux/releases/download/v1.0/dux_1.0_darwin_amd64.tar.gz"
      sha256 "99a8ef77a98228fe0684d125ba344d97870dd701a07083687ca62bdb8a050273"

      def install
        bin.install "dux"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/nikitasova/dux/releases/download/v1.0/dux_1.0_darwin_arm64.tar.gz"
      sha256 "b40fa90719bc2714a825070a79d4857d2991bf466047c9a8bb5c4d6db78cb00b"

      def install
        bin.install "dux"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/nikitasova/dux/releases/download/v1.0/dux_1.0_linux_amd64.tar.gz"
      sha256 "77807b5b2684ad702e64b289ec5d0ac4be3ff8571c883f1821337096fe51cbb2"
      def install
        bin.install "dux"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/nikitasova/dux/releases/download/v1.0/dux_1.0_linux_arm64.tar.gz"
      sha256 "8a1ea9302a112c01c226820cbdcc72bf2ee142c884a2029f58a1f0e079bd7626"
      def install
        bin.install "dux"
      end
    end
  end

  test do
    system "#{bin}/dux version"
  end
end
